### ISSUE TITLE
Sometimes bots just stand there and do nothing.

### ISSUE THREAD

**Issue by Anonymous3-a** [EISHU-MT/bs_bots#1]
Sometimes, the bots just stop moving and do nothing. In the attached video, I died. Notice on the left, the bot's HP isn't going down.
![2024-08-04 07-48-40](https://github.com/user-attachments/assets/d698d54f-e53d-4def-b26b-641c834e7872)
(Hey, tip: make an issue template. I'm not really too sure what to put, I'll put this:).
OS: Artix Linux
Minetest Ver: 5.9.0-dev
<s>No idea if there's logs somewhere I should put?</s>
EDIT: I am now running Minetest from my terminal. I'll get applicable logs there.

**Comment by nisep9** [comment]
hii, tyy so much for reporting the bug, now it might is fixed in the new release of the bots mod
hunter.lua=>Hunt()=> fixed
